### ISSUE TITLE
Export Player type?

### ISSUE THREAD

**Issue by rparrett** [vleue/jornet#64]
I'm persisting the player identity and using `as_player` and it would be convenient if this type were exported by `bevy_jornet`. It's already conveniently `Serialize, Deserialize`.

**Comment by mockersf** [comment]
this was meant to be exposed, fixed in 6fae3efde34e7e5f20513bda77ebac17d64c9ded 👍  and released in https://crates.io/crates/bevy_jornet/0.1.4
