### ISSUE TITLE
Allow bevy_jornet users to set jornet server host

### ISSUE THREAD

**Issue by rparrett** [vleue/jornet#68]
There's currently no API for doing this, and the field in `Leaderboard` is private so it doesn't seem possible to work around.

**Comment by mockersf** [comment]
added an api in 19b4c4f2b9248091790fa246969d1ab7d41a0767 to build the plugin with a custom host, released in https://crates.io/crates/bevy_jornet/0.1.4

**Comment by mockersf** [comment]
https://docs.rs/bevy_jornet/0.1.4/bevy_jornet/struct.JornetPlugin.html#method.with_host
